config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :clients
  resources :careers
  resources :contacts
  resources :abouts
  resources :homes
  resources :services
  resources :products
  resources :pictures

  root 'homes#index'
end

app/models/about.rb
class About < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5 }
  validates :subtitle, presence: true
  validates :body, presence: true
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/career.rb
class Career < ApplicationRecord
  validates :fullname, presence: true, length: { minimum: 5 }
  validates :email, presence: true, uniqueness: true
  validates :github_repo, presence: true, uniqueness: true
  validates :portfolio, presence: true
  validates :cover, presence: true
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :service

  validates :category, presence: true
  validates :type, presence: true
  validates :email, presence: true, uniqueness: true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :username, presence: true, length: { minimum: 5 }
  validates :email, presence: true, uniqueness: true
  validates :subject, presence: true
  validates :message, presence: true
end

app/models/home.rb
class Home < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true

  has_attached_file :image, styles: { medium: '300x300>', thumb: '100x100>' }
  validates_attachment_content_type :image, content_type: %r{\Aimage/.*\z}
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :product

  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :pictures, dependent: :destroy
  belongs_to :service

  validates :category, presence: true
  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :products, dependent: :destroy
  has_many :clients, dependent: :destroy

  validates :category, presence: true
  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  before_action :set_about, only: [:show, :edit, :update, :destroy]

  # GET /abouts
  # GET /abouts.json
  def index
    @abouts = About.all
  end

  # GET /abouts/1
  # GET /abouts/1.json
  def show
  end

  # GET /abouts/new
  def new
    @about = About.new
  end

  # GET /abouts/1/edit
  def edit
  end

  # POST /abouts
  # POST /abouts.json
  def create
    @about = About.new(about_params)

    respond_to do |format|
      if @about.save
        format.html { redirect_to @about, notice: 'About was successfully created.' }
        format.json { render :show, status: :created, location: @about }
      else
        format.html { render :new }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abouts/1
  # PATCH/PUT /abouts/1.json
  def update
    respond_to do |format|
      if @about.update(about_params)
        format.html { redirect_to @about, notice: 'About was successfully updated.' }
        format.json { render :show, status: :ok, location: @about }
      else
        format.html { render :edit }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abouts/1
  # DELETE /abouts/1.json
  def destroy
    @about.destroy
    respond_to do |format|
      format.html { redirect_to abouts_url, notice: 'About was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_about
      @about = About.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def about_params
      params.require(:about).permit(:title, :subtitle, :body)
    end
end

app/controllers/careers_controller.rb
class CareersController < ApplicationController
  before_action :set_career, only: [:show, :edit, :update, :destroy]

  # GET /careers
  # GET /careers.json
  def index
    @careers = Career.all
  end

  # GET /careers/1
  # GET /careers/1.json
  def show
  end

  # GET /careers/new
  def new
    @career = Career.new
  end

  # GET /careers/1/edit
  def edit
  end

  # POST /careers
  # POST /careers.json
  def create
    @career = Career.new(career_params)

    respond_to do |format|
      if @career.save
        format.html { redirect_to @career, notice: 'Career was successfully created.' }
        format.json { render :show, status: :created, location: @career }
      else
        format.html { render :new }
        format.json { render json: @career.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /careers/1
  # PATCH/PUT /careers/1.json
  def update
    respond_to do |format|
      if @career.update(career_params)
        format.html { redirect_to @career, notice: 'Career was successfully updated.' }
        format.json { render :show, status: :ok, location: @career }
      else
        format.html { render :edit }
        format.json { render json: @career.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /careers/1
  # DELETE /careers/1.json
  def destroy
    @career.destroy
    respond_to do |format|
      format.html { redirect_to careers_url, notice: 'Career was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_career
      @career = Career.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def career_params
      params.require(:career).permit(:fullname, :email, :github_repo, :portfolio, :cover)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: %i[show edit update destroy]

  def index
    @pagy, @homes = pagy(Home.all.order('created_at DESC'), items: 1)
  end

  def show
    @home = Home.find(params[:id])
    @homes = Home.order('created_at desc').limit(4).offset(1)
  end

  def new
    @home = Home.new
  end

  private
    def set_home
      @home = Home.find(params[:id])
    end

    def home_params
      params.require(:home).permit(:title, :body)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def bootstrap_class_for(flash_type)
    {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end
end

app/helpers/careers_helper.rb
module CareersHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/abouts/_form.html.erb
<%= form_with(model: about, local: true) do |form| %>
  <% if about.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(about.errors.count, "error") %> prohibited this about from being saved:</h2>

      <ul>
      <% about.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/abouts/edit.html.erb
<h1>Editing About</h1>

<%= render 'form', about: @about %>

<%= link_to 'Show', @about %> |
<%= link_to 'Back', abouts_path %>

app/views/abouts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Abouts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Subtitle</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @abouts.each do |about| %>
      <tr>
        <td><%= about.title %></td>
        <td><%= about.subtitle %></td>
        <td><%= about.body %></td>
        <td><%= link_to 'Show', about %></td>
        <td><%= link_to 'Edit', edit_about_path(about) %></td>
        <td><%= link_to 'Destroy', about, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New About', new_about_path %>

app/views/abouts/new.html.erb
<h1>New About</h1>

<%= render 'form', about: @about %>

<%= link_to 'Back', abouts_path %>

app/views/abouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @about.title %>
</p>

<p>
  <strong>Subtitle:</strong>
  <%= @about.subtitle %>
</p>

<p>
  <strong>Body:</strong>
  <%= @about.body %>
</p>

<%= link_to 'Edit', edit_about_path(@about) %> |
<%= link_to 'Back', abouts_path %>

app/views/careers/_form.html.erb
<%= form_with(model: career, local: true) do |form| %>
  <% if career.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(career.errors.count, "error") %> prohibited this career from being saved:</h2>

      <ul>
      <% career.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fullname %>
    <%= form.text_field :fullname %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :github_repo %>
    <%= form.text_field :github_repo %>
  </div>

  <div class="field">
    <%= form.label :portfolio %>
    <%= form.text_field :portfolio %>
  </div>

  <div class="field">
    <%= form.label :cover %>
    <%= form.text_area :cover %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/careers/edit.html.erb
<h1>Editing Career</h1>

<%= render 'form', career: @career %>

<%= link_to 'Show', @career %> |
<%= link_to 'Back', careers_path %>

app/views/careers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Careers</h1>

<table>
  <thead>
    <tr>
      <th>Fullname</th>
      <th>Email</th>
      <th>Github repo</th>
      <th>Portfolio</th>
      <th>Cover</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @careers.each do |career| %>
      <tr>
        <td><%= career.fullname %></td>
        <td><%= career.email %></td>
        <td><%= career.github_repo %></td>
        <td><%= career.portfolio %></td>
        <td><%= career.cover %></td>
        <td><%= link_to 'Show', career %></td>
        <td><%= link_to 'Edit', edit_career_path(career) %></td>
        <td><%= link_to 'Destroy', career, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Career', new_career_path %>

app/views/careers/new.html.erb
<h1>New Career</h1>

<%= render 'form', career: @career %>

<%= link_to 'Back', careers_path %>

app/views/careers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fullname:</strong>
  <%= @career.fullname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @career.email %>
</p>

<p>
  <strong>Github repo:</strong>
  <%= @career.github_repo %>
</p>

<p>
  <strong>Portfolio:</strong>
  <%= @career.portfolio %>
</p>

<p>
  <strong>Cover:</strong>
  <%= @career.cover %>
</p>

<%= link_to 'Edit', edit_career_path(@career) %> |
<%= link_to 'Back', careers_path %>

app/views/homes/_form.html.erb
<%= form_with(model: home, local: true) do |form| %>
  <% if home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
<div class="slider">
  <div class="Modern-Slider content-section" id="top">
    <div class="item item-1">
      <div class="img-fill">
      <% @homes.each do |home| %>
        <%= image_tag home.image.url, class: "image" %>
      <% end %>
      <div class="info">
        <div>
          <% @homes.each do |home| %>
            <h1><%= home.title %></h1>
            <p><%= home.body %></p>
          <% end %>

          <div class="white-button button">
            <a href="#">Our Services</a>
          </div>

          <div class="white-button button">
            <a href="#">Our Products</a>
          </div>

        </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="page-content">

  <section id="featured" class="content-section">
    <div class="section-heading">
      <h1>Featured<br><em>Places</em></h1>
      <p>Praesent pellentesque efficitur magna,<br>sed pellentesque neque malesuada vitae.</p>
    </div>
    <div class="section-content">
      <div class="owl-carousel owl-theme">
        <div class="item">
          <div class="image">
            <img src="assets/featured_1.jpg" alt="">
            <div class="featured-button button">
              <a href="#">Continue Reading</a>
            </div>
          </div>
          <div class="text-content">
            <h4>Lorem ipsum dolor</h4>
            <span>Proin et sapien</span>
            <p>#1 You are allowed to use Sentra Template for your business.</p>
          </div>
        </div>
        <div class="item">
          <div class="image">
            <img src="assets/featured_2.jpg" alt="">
            <div class="featured-button button">
              <a href="#">Continue Reading</a>
            </div>
          </div>
          <div class="text-content">
            <h4>Phasellus a lacus ac odio</h4>
            <span>Maximus</span>
            <p>#2You <strong>can post</strong> a screenshot and a  Thank you.</p>
          </div>
        </div>
        <div class="item">
          <div class="image">
            <img src="assets/featured_3.jpg" alt="">
            <div class="featured-button button">
              <a href="#">Continue Reading</a>
            </div>
          </div>
          <div class="text-content">
            <h4>Proin sit amet fringilla</h4>
            <span>Vulputate</span>
            <p>#3 Aliquam mollis lacus eget metus efficitur lobortis.</p>
          </div>
        </div>
        <div class="item">
          <div class="image">
            <img src="assets/featured_2.jpg" alt="">
            <div class="featured-button button">
              <a href="#">Continue Reading</a>
            </div>
          </div>
          <div class="text-content">
            <h4>In volutpat augue lectus</h4>
            <span>Elementum</span>
            <p>#4 Aliquam mollis lacus eget metus efficitur lobortis.</p>
          </div>
        </div>
        <div class="item">
          <div class="image">
            <img src="assets/featured_1.jpg" alt="">
            <div class="featured-button button">
              <a href="#">Continue Reading</a>
            </div>
          </div>
          <div class="text-content">
            <h4>Cras commodo odio</h4>
            <span>Aliquam</span>
            <p>#5 Mauris lacinia pretium libero, ut tincidunt.</p>
          </div>
        </div>
        <div class="item">
          <div class="image">
            <img src="assets/featured_3.jpg" alt="">
            <div class="featured-button button">
              <a href="#">Continue Reading</a>
            </div>
          </div>
          <div class="text-content">
            <h4>Sed at massa turpis</h4>
            <span>Curabitur</span>
            <p>#6 Vestibulum tincidunt ornare ligula vel molestie..</p>
          </div>
        </div>
        <div class="item">
          <div class="image">
            <img src="assets/featured_2.jpg" alt="">
            <div class="featured-button button">
              <a href="#">Continue Reading</a>
            </div>
          </div>
          <div class="text-content">
            <h4>Aliquam mollis lacus</h4>
            <span>Suspendisse</span>
            <p>#7 Suspendisse suscipit nulla sed nisl fermentum.</p>
          </div>
        </div>
        <div class="item">
          <div class="image">
            <img src="assets/featured_1.jpg" alt="">
            <div class="featured-button button">
              <a href="#">Continue Reading</a>
            </div>
          </div>
          <div class="text-content">
            <h4>Mauris lacinia pretium</h4>
            <span>Vestibulum</span>
            <p>#8 Suspendisse suscipit nulla sed nisl fermentum.</p>
          </div>
        </div>
        <div class="item">
          <div class="image">
            <img src="assets/featured_3.jpg" alt="">
            <div class="featured-button button">
              <a href="#">Continue Reading</a>
            </div>
          </div>
          <div class="text-content">
            <h4>Proin sit amet fringilla erat</h4>
            <span>Convallis</span>
            <p>#9 Suspendisse suscipit nulla sed nisl fermentum.</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section id="video" class="content-section">
    <div class="row">
      <div class="col-md-12">
        <div class="section-heading">
          <h1>This is a <em>company</em> presentation.</h1>
          <p>Praesent pellentesque efficitur magna, sed pellentesque.</p>
        </div>
        <div class="text-content">
          <p>In eget ipsum sed lorem vehicula luctus. Curabitur non.</p>
        </div>
        <div class="accent-button button">
          <a href="#">Continue Reading</a>
        </div>
      </div>
      <div class="col-md-12">
        <div class="box-video">
          <div class="bg-video" style="background-image: url(https://unsplash.imgix.net/photo-1425036458755-dc303a604201?fit=crop&fm=jpg&q=75&w=1000);">
            <div class="bt-play">Play</div>
          </div>
          <div class="video-container">
            <iframe width="100%" height="520" src="https://www.youtube.com/embed/j-_7Ub-Zkow?rel=0&amp;showinfo=0" frameborder="0" allowfullscreen="allowfullscreen"></iframe>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section id="contact" class="content-section">
    <div id="contact-content">
      <div class="section-heading">
        <h1>Contact<br><em>Layout One</em></h1>
        <p>Curabitur hendrerit. <br>Phasellus.</p>
      </div>
      <div class="section-content">
        <form id="contact" action="#" method="post">
          <div class="row">
            <div class="col-md-4">
              <fieldset>
                <input name="name" type="text" class="form-control" id="name" placeholder="Your name..." required="">
              </fieldset>
            </div>
            <div class="col-md-4">
              <fieldset>
                <input name="email" type="email" class="form-control" id="email" placeholder="Your email..." required="">
              </fieldset>
            </div>
             <div class="col-md-4">
              <fieldset>
                <input name="subject" type="text" class="form-control" id="subject" placeholder="Subject..." required="">
              </fieldset>
            </div>
            <div class="col-md-12">
              <fieldset>
                <textarea name="message" rows="6" class="form-control" id="message" placeholder="Your message..." required=""></textarea>
              </fieldset>
            </div>
            <div class="col-md-12">
              <fieldset>
                <button type="submit" id="form-submit" class="btn">Send Message Now</button>
              </fieldset>
            </div>
          </div>
        </form>
      </div>
    </div>
  </section>

</div>

app/views/homes/new.html.erb
<h1>New Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @home.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @home.body %>
</p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>